# Generated by Django 6.0.3 on 2026-04-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('labels', models.CharField(blank=True, max_length=500, null=True)),
                ('last_updated', models.DateTimeField()),
                ('comment_count', models.IntegerField(default=0)),
                ('difficulty', models.CharField(max_length=20)),
            ],
        ),
    ]
